### ISSUE TITLE
Improved resolution

### ISSUE THREAD

**Issue by Avokadomos** [jetelain/Arma3Map#11]
Hello! You've done amazing work here. I'm very interested in the map export. It looks much better than the other export methods.

I was hoping that you could add some way of increasing the zoom level of the map, if it's not asking too much. It would be nice to have one or two more zoom levels, so that you can get a good view on the streets and buildings for close quarter combat.

**Comment by jetelain** [comment]
Hi, It's possible, I will work on it

**Comment by Avokadomos** [comment]
Awesome! Looking forward to it.

**Comment by jetelain** [comment]
Tests OK on Chernarus 2020, now we need to regenerate all maps !

**Comment by z3r03nna** [comment]
Hi, I tried to create a pull request for a fresh map of (beketov) https://steamcommunity.com/sharedfiles/filedetails/?id=743968516

But I cant upload it because the github max file size was reached (See details below). Do you have any idea how to circumvent that? Or any other upload channel? Is this a problem for the other maps on HiRes too? 

![grafik](https://user-images.githubusercontent.com/18697724/125683723-70c138e2-f7ac-4fb2-8efe-bbfdc5ba08e0.png)
