### ISSUE TITLE
Request for comment: Replace this repository by a web application ?

### ISSUE THREAD

**Issue by jetelain** [jetelain/Arma3Map#71]
Hi,
This repository is becoming really huge, and wont be able to scale a lot more.
Git LFS could be a solution, but GitHub pricing would make it very expensive.

I am considering to remplace this repository by a web application running on one of my existing server, with mirroring on existing OVH CDN hosting (maps-data.plan-ops.fr).

The web application would allow:
- direct upload from the map exporter mod
- manual upload of images
- support for other games
- a moderation system to prevent abuse
- easy to mirror system

What do you think about this ? Do you see any alternative ?

**Comment by Grezvany13** [comment]
My 2 cents:

Git LFS won't solve the problem, since there are no large files, just a massive amount. And the repository is just massive with the large amount of files (which makes it hard to push/pull).

Building a custom application might be a solution, but takes time and is either prone to errors/abuse or requires a lot of manual moderation.

My suggestion would be to split the repository into several parts:
- A3Map-mod (now: [@arma3MapExporter](https://github.com/jetelain/Arma3Map/tree/master/%40arma3MapExporter))
- A3Map-exporter (now: [MapExporter](https://github.com/jetelain/Arma3Map/tree/master/MapExporter))
- A3Map (now: this repository for web access)
- A3Map-<terrain_name> (each terrain having it's own repository)

A3Map can then have submodules to the terrains, so they're available, but can be maintained separately.
And although I'm personally not a big fan of submodules, it's probably the best way to make it more maintainable at this scale.

**Comment by jetelain** [comment]
Thank you for the feedback. Using git at large scale for binary objects have performance issue that seems cant be solved. GitHub Pages have not been able to run for multiples years, because the checkout operation timeout. LFS would have the same issue, ad everything is downloaded again at each run.

Current infrastructure around git requires a lot of manual work. I think the moderation will be more easier.

I opted for the web application with the [GameMapStorage](https://github.com/jetelain/GameMapStorage) project. It's up and running on https://atlas.plan-ops.fr/maps/arma3

The application is able to get data from this repo, or anything with similar structure. I dont known yet how I will manage moderation, keeping git repos as entry point for contribution could be an option.
